### ISSUE TITLE
发布NutzWeb 1.b.52

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz-web#3]
RT

**Comment by ywjno** [comment]
pom 里面的 jetty 的版本要不要变到9.0？

**Comment by wendal** [comment]
改咯

**Comment by ywjno** [comment]
nutz 里面的依赖要不要一起跟着改？

**Comment by wendal** [comment]
nutz只是测试的时候用到jetty啊

**Comment by ywjno** [comment]
jetty 7 的 servlet-api 版本是 2.5，jetty 9 的是 3.1，不进行修改的话能启动 jetty 么

**Comment by wendal** [comment]
那就不变了

**Comment by ywjno** [comment]
昨天试了试，nutz 升级到 jetty 9 后，测试 mvc 相关的 mock 的代码需要实现接口中新添加的方法，未经过实际项目进行测试，估计问题不大？

**Comment by wendal** [comment]
jdk6 会编译不过吧?

**Comment by ywjno** [comment]
这倒没试过，本地机器只有 jdk8

**Comment by ywjno** [comment]
那把 fb0820c 的那个提交当成是1.b.52给推送到中央库？

**Comment by wendal** [comment]
恩, OK

**Comment by ywjno** [comment]
或者把现在 master 上有关 jetty9 的代码都给弄到一个分支上，然后把这部分代码打个 tag 当成是 1.b.52 后给推送到中央库

**Comment by wendal** [comment]
最新的代码不兼容nutz 1.b.52 去掉了代码,编译上传了

```
Mvcs.dynamic_ann_paths = annPaths;
Mvcs.dynamic_modules = modules;
```
