### ISSUE TITLE
nutz-web使用websocket 协议访问路径问题

### ISSUE THREAD

**Issue by sunhai1988** [nutzam/nutz-web#6]
用 nohup mvn exec:java -Dexec.mainClass="org.nutz.web.WebLauncher"   启动web服务后  websocket协议访问报404 

`WebSocket connection to 'wss://****.tv/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404`

如果用：jetty:run  能正常相应onmessage  

讨论帖：https://nutz.cn/yvr/t/0ducqp41m6he6p4hqtco3oetj4

**Comment by wendal** [comment]
嗯

**Comment by wendal** [comment]
已经没问题了
