### ISSUE TITLE
NutOnlyWebServer是否也能支持app-rs配置？

### ISSUE THREAD

**Issue by qinerg** [nutzam/nutz-web#7]
NutOnlyWebServer很好用，可以不用配web.xml直接运行。对于rest api类程序来说很适用。
但是否可以也对供对静态文件的支持，如配置 app-rs 后，允许访问其下的静态文件？
另外，是否可以关闭 jetty 默认的列目示的功能？

**Comment by wendal** [comment]
已经ok了
