### ISSUE TITLE
考虑重构并迁入nutzmore

### ISSUE THREAD

**Issue by wendal** [nutzam/nutz-web#8]
想想

**Comment by zozoh** [comment]
额，你现在的思路是 nutzmore 放所有的非核心包的扩展对吧？

我原来的思路是和 Apache 那个类似。一开始都放到 nutzmore 里，如果觉得不错，就提出来作为顶级项目

我们现在有的顶级项目可能需要整理一下， nutzmongo 好像用的人不多，放到 nutzmore 里咯
nutz-web 到是作为顶级可能比较好一点吧

**Comment by wendal** [comment]
soga, nutzmongo已经并入nutzmore, nutz-web的jetty启动器由nutzboot-starter-jetty替代
